# postgres used only for the psql client
FROM postgres:latest

RUN apt-get update && \
    apt-get install -y perl curl make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://cpanmin.us | perl - App::cpanminus
RUN cpanm TAP::Parser::SourceHandler::pgTAP

COPY ./tests/ /tests/
WORKDIR /tests
CMD ["./run_tests.sh"]