services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - database