FROM alpine:latest
RUN apk --no-cache add postgresql16-client curl make perl

RUN curl -L https://cpanmin.us/ -o cpanm
RUN chmod +x cpanm
RUN ./cpanm -n --no-wget --curl TAP::Parser::SourceHandler::pgTAP

COPY ./tests/ /tests/
WORKDIR /tests
CMD ["./run_tests.sh"]